### PR TITLE
re-implement yaml-get and yaml-keys in bash

### LINKED ISSUE #80: Procfile parsing seems very fragile
Earlier today, while trying to deploy an app to Dokku I had a simple Procfile which looked like this
```
web:python server.py
```

Can you spot the error? Yeah, I couldn't either. As it turns out, herokuish expects a space after the colon and threw [this](https://gist.github.com/andor44/00ea298f6795dc383549) nasty stack trace in my face. Neither foreman nor "real" Heroku seems to care about the presence of the space, or lack thereof. The error message is also really cryptic and nondescript, and it was just really a random guess of mine to try it with a space. A better error message, or more lenient parsing of the Procfile would be really nice.

### PR DESCRIPTION
**Pull request by michaelshobbs**
closes #80

### CODE REVIEW

**Comment by michaelshobbs** [comment]
ping @progrium @andor44

**Comment by progrium** [comment]
*stares at it a moment*

This works? Maaaaybe write a test? :grinning:

**Comment by michaelshobbs** [comment]
The entire test suite hits this code.....

**Comment by josegonzalez** [comment]
:+1: merge.

**Comment by michaelshobbs** [comment]
I can take a crack at re-implementing in golang vs. bash

**Comment by progrium** [comment]
It's fine :)

**Comment by michaelshobbs** [comment]
Actually thinking further here. The output of `release` is yaml. So we want to keep that functionality as is. The reported issue was in parsing `Procfiles` specifically. This uses bash string substitution to accomplish simple colon-separated format parsing.

**Pull request merged**
