### PR TITLE
Vendored dependencies using godep

### PR DESCRIPTION
**Pull request by johanneswuerbach**
herokuish does not compile with go-basher master, lock go-basher to an
older version and prevent further breakage by vendoring compile deps

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
I looks like circleci is still failing because of https://github.com/golang/go/issues/8850, which is fixed in go 1.4. I couldn't find a way to specify a different go version on circle. Ideas?

//cc @progrium

**Comment by johanneswuerbach** [comment]
Fixed :smile:! The actual issue was a custom gitconfig pre-installed on CircleCI.

**Comment by progrium** [comment]
Yep, discovered a day before you did. Also applied same workaround you found. But I'm going to suggest not vendoring just yet. If the build breaks because of a dependency on a library I'm writing, I'd rather just fix it here. If it were somebody else's library that breaks the build, then I'd consider vendoring before the next release. But I'd rather keep workflow and tooling as simple as it can, and encourage keeping things up to date.

**Comment by johanneswuerbach** [comment]
Makes sense to me.

**Pull request closed without merging**
