### PR TITLE
implement heroku-like buildpack detect order and output

### LINKED ISSUE #133: Detect appropriate buildpack like Heroku
- We'd like to detect the appropriate buildpack in the same order as Heroku
  - https://devcenter.heroku.com/articles/buildpacks
- Additionally, we'd like to show **all** valid buildpacks for an app
image 2016-03-29 at 6 05 39 pm

### PR DESCRIPTION
**Pull request by michaelshobbs**
Implements new detect order based on [Heroku](https://devcenter.heroku.com/articles/buildpacks#officially-supported-buildpacks).

```
multi
ruby
nodejs
clojure
python
java
gradle
grails
scala
play
php
go
erlang
static
emberjs
```

New output example:
```
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi ruby nodejs python
-----> Multipack app detected
```

closes #133

### CODE REVIEW

**Comment by michaelshobbs** [comment]
@josegonzalez Open question, do we move emberjs between `ruby` and `nodejs` or leave it at the end?

Context: in the current state, emberjs will never automatically be detected because the nodejs buildpack matches first.

**Comment by u2mejc** [comment]
@michaelshobbs looks like emberjs isn't officially supported upstream? Do you want to keep it here as a an offical?

**Comment by michaelshobbs** [comment]
@u2mejc Yes but only because it's the only `tgz` buildpack I know and I think we need a test case for those buildpack types. To be clear, though, `erlang`, `static` and `multi` are also not on the official list.

**Comment by josegonzalez** [comment]
Leave it at the end. Heroku also doesn't autodetect them, correct? We just want to make sure we support the buildpack i think.

**Comment by michaelshobbs** [comment]
That is correct. Works for me.

**Pull request merged**
