### PR TITLE
Added Play V1 example app

### PR DESCRIPTION
**Pull request by johanneswuerbach**
The play buildpack only works for play 1.x apps. Play 2.0 apps are using the scala buildpack

https://github.com/heroku/heroku-buildpack-play#heroku-buildpack-play
> Note: This buildpack only applies to Play 1.2.x apps. Play 2.x apps are handled by the Scala buildpack

Deis PR: https://github.com/deis/example-play/pull/1
Based on: https://github.com/gliderlabs/herokuish/pull/6

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
I also had to bump the play BP version as the old play BP seems broken with cedar-14.
Changes:
https://github.com/heroku/heroku-buildpack-play/compare/ceede86...v23

**Comment by progrium** [comment]
Can you drop the first two commits again?

**Comment by johanneswuerbach** [comment]
Dropped.

**Comment by progrium** [comment]
Thanks!

**Pull request merged**
