### PR TITLE
Build a container including cedarish and herokuish

### PR DESCRIPTION
**Pull request by johanneswuerbach**
This allows to build containers using herokuish, which bundle the correct version of cedarish and are tested against it

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Some buildpacks require specific cedarish changes (like https://github.com/progrium/cedarish/issues/16). Having a published image containing the correct cedarish and herokuish versions allows developers to stop caring about this dependency and simplifies using herokuish 

Example:
```
FROM progrium/cedarish:cedar14
RUN curl https://github.com/gliderlabs/herokuish/releases/download/v0.2.0/herokuish_0.2.0_linux_x86_64.tgz \
		--silent -L | tar -xzC /bin
```
becomes:
```
FROM gliderlabs/herokuish:v3
```

**Comment by progrium** [comment]
I like this as a convenience, but what are specific use cases? Herokuish is designed to work with cedarish, but is flexible enough to be used on other images, and also not even be Docker specific. I like the main artifact being a binary for this reason. 

Versioning a Docker image would be another version for the same project. I'm wondering if a decent compromise here is to make a Docker Hub image that follows master and release, and if you want to pin to specific versions you manually base on cedarish and install Herokuish?

**Comment by progrium** [comment]
Curious if @bacongobbler has thoughts on this.

**Comment by progrium** [comment]
Also keep in mind that buildstep becoming [buildkit](https://github.com/progrium/dokku/wiki/Refactoring#buildstep-to-become-buildkit) will be the preferred level of abstraction for most users anyway.

**Comment by johanneswuerbach** [comment]
> Versioning a Docker image would be another version for the same project. I'm wondering if a decent compromise here is to make a Docker Hub image that follows master and release, and if you want to pin to specific versions you manually base on cedarish and install Herokuish?

Yes, this was my idea. Continue to release a binary and tag the docker image in addition with the same number. A bit like etcd is doing it https://github.com/coreos/etcd/releases

> Herokuish is designed to work with cedarish

Yep, but it looks like herokuish might not work with all versions of cedarish and having an image would allow projects like buildstep to just increment one version instead of verifying dependencies. My main goal for this PR is to ship a container, which was tested bit-by-bit.

**Comment by progrium** [comment]
Okay, the difference in what I'm proposing and what you're proposing is that I'm saying we *only* tag and push images called `master` and `release`, not specific versions for every release. 

But I think I'm being persuaded. Doing image tags/pushes per version means we can't do Automated Builds, but I think since most users will not be using this directly that's not as big a concern. And also since the container would be a secondary/convenience artifact to the binary tarball.

**Comment by johanneswuerbach** [comment]
Oh I don't think we should do automated hub builds, but push to docker hub during `make release`. This would also ensure, that the container actually passed all tests.

**Comment by progrium** [comment]
I see that now in your source.

**Comment by progrium** [comment]
Is there an easy way to collaborate on PR commits? I wanted to change a few things and it seems like it would be better to do that before merging into master and ending discussion here.

**Comment by johanneswuerbach** [comment]
Another reason, why I would like to have tagged releases, is to avoid workarounds like https://github.com/deis/deis/blob/master/builder/image/Dockerfile#L43, which is currently done in deis to lock the cedarish version.

Sure, I just gave you push access to my repo https://github.com/johanneswuerbach/herokuish/tree/containerize.

**Comment by progrium** [comment]
That is not a workaround, that is intentional. Downloading and importing a
gzip'd tar of cedarish is significantly faster than downloading any Docker
Hub image based on cedarish. That is another thing to consider and why
these projects are set up this way. I'm likely to do something similar in
buildkit/buildstep to ensure your initial experience is as fast as
possible. This is also why I see a container of Herokuish a convenience and
not something I would normally use.

On Fri, Feb 13, 2015 at 8:08 AM, Johannes Würbach <notifications@github.com>
wrote:

> Another reason, why I would like to have tagged releases, is to avoid
> workarounds like
> https://github.com/deis/deis/blob/master/builder/image/Dockerfile#L43,
> which is currently done in deis to lock the cedarish version.
>
> Sure, I just gave you push access to my repo
> https://github.com/johanneswuerbach/herokuish/tree/containerize.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/pull/14#issuecomment-74258256>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
*Reposting for markdown*

That is not a workaround, that is [intentional](https://github.com/deis/deis/issues/1027). Although they don't need to host their own tarball and I wouldn't call it a hack ... downloading and importing a gzip'd tar of cedarish is significantly faster than downloading any Docker Hub image based on cedarish. That is another thing to consider and why these projects are set up this way. I'm likely to do something similar in buildkit/buildstep to ensure your initial experience is as fast as possible. This is also why I see a container of Herokuish a convenience and not something I would normally use.

And that has nothing to do with locking versions since all official project artifacts are versioned.

At the end of the day, the default strategy in buildkit will download Herokuish and use the right version of cedarish based on the output of Herokuish ... it will be orchestrating its own Herokuish image. And if that's the primary way people actually use any of this, there isn't a big reason to do that here. Especially if even Deis ends up using buildkit, which is the plan to make happen.

**Comment by progrium** [comment]
So now I'm back on the fence.

**Comment by bacongobbler** [comment]
> Curious if @bacongobbler has thoughts on this.

I'm a bit busy this morning but I will get back to you on this one. :)

**Comment by progrium** [comment]
We talked through it more over IRC and came to the conclusion we don't need
Docker Hub images pushed, but having cedarish-style tarballs that include
herokuish on cedarish should be released as well as the standalone binary.

On Fri, Feb 13, 2015 at 8:47 AM, Matthew Fisher <notifications@github.com>
wrote:

> Curious if @bacongobbler <https://github.com/bacongobbler> has thoughts
> on this.
>
> I'm a bit busy this morning but I will get back to you on this one. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/pull/14#issuecomment-74264020>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by johanneswuerbach** [comment]
Yes, downloading speed was one reason, but wouldn't this go away with docker distribution protocol v2 (parallel layer downloading), which should land in docker 1.6? Having a herokuish container would still allow to download a tarball, but would remove the requirement to keep the your cedarish (container / tarball) and herokuish in sync.

> At the end of the day, the default strategy in buildkit will download Herokuish and use the right version of cedarish based on the output of Herokuish ... it will be orchestrating its own Herokuish image.

Isn't this the same as providing a herokuish container on docker hub?

For me one of the main advantages of docker is to have a container with fixed dependencies from CI to prod, which means a herokuish build with CI tested buildpacks on a specific cedarish release.

**Comment by progrium** [comment]
We can revisit Docker Hub when their new distribution stuff is out and we can test speed, etc.

**Comment by progrium** [comment]
Master is currently using a Dockerfile that uses latest cedarish. This will replace current Buildstep. However, Herokuish has *stopped* tracking cedarish releases for several reasons:
1. Too many people ask about security updates and rebuilding base images. This breaks with release artifacts. You *need* to not be pinned so people can rebuild and get updates. 
1. Instead, pinning and byte-for-byte releases should happen as far downstream as possible, otherwise every step becomes a bottleneck to security updates. 
1. A [PR](https://github.com/heroku/stack-images/pull/15) was opened against heroku/stack-images in an attempt to deprecate cedarish and just have Heroku manage the base image. This may come at the cost of artifact releases anyway.
1. Removing cedarish tracking removed a lot of the ugly build code of Herokuish

**Pull request closed without merging**
