### PR TITLE
Release 0.5.0 - Bump heroku stack to Heroku:18

### PR DESCRIPTION
**Pull request by swistaczek**
Hello 👋 ,
This PR updates base Heroku (heroku-build) stack from tag 16 to latest supported tag 18.

### CODE REVIEW

**Comment by josegonzalez** [comment]
This pull request should target master, and we can handle the release process. Mind updating the PR to reflect that?

**Comment by swistaczek** [comment]
Hey @josegonzalez! Thanks for the reply. I fixed the base to master. Please let me know do you want me to rollback version things (I followed readme saying `Anybody can propose a release` but I can remove my version changes ;)).

**Comment by josegonzalez** [comment]
Yeah my preference here is to not introduce new functionality in the same PR as the release PR. We can do a release PR after this change is introduced. Makes it easier to suss out what was in the release by looking at merge requests.

/cc @michaelshobbs as this is going to need review/consideration. I'm not _concerned_, though I think you might be in a position to comment on whether we want this now or want to wait.

**Comment by josegonzalez** [comment]
Yeah my preference here is to not introduce new functionality in the same PR as the release PR. We can do a release PR after this change is introduced. Makes it easier to suss out what was in the release by looking at merge requests.

/cc @michaelshobbs as this is going to need review/consideration. I'm not _concerned_, though I think you might be in a position to comment on whether we want this now or want to wait.

**Pull request closed without merging**
