### PR TITLE
Resolves #30 - Incorrect parsing of Procfile commands

### LINKED ISSUE #30: Incorrect parsing of Procfile commands
Procfile command parsing is using ```eval``` (https://github.com/gliderlabs/herokuish/blame/41aeaed24f778bf9582f9112e2cf79418f7fc8cc/include/procfile.bash#L21):
```
unprivileged /bin/bash -c "$(eval echo $@)"
```

Doing ```$(eval <blah>)``` doesn't serve a purpose, it just breaks commands that include quotes.

my-quotes.sh:
```
#!/bin/sh
echo "echo \$@ = $(echo $@)"
echo "eval echo \$@ = $(eval echo $@)"
```

Execution example:
```
./my-quotes.sh sh -c \"echo \$PORT\"
echo $@ = sh -c "echo $PORT"
eval echo $@ = sh -c echo 10
```

Note that the quotes have been dropped. Also, variable expansion has taken place, which we *do* want in Herokuish. However, the variable expansion will be performed by ```/bin/bash -c``` on the same line in ```procfile.bash```.

### PR DESCRIPTION
**Pull request by Benjamin-Dobell**
Resolves #30

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
Is there anything I can do to improve this pull request?

#30 contains a small stand-alone example of why the use of ```eval``` breaks commands with quotes.

Are there any tests I would need to run/write etc?

**Comment by josegonzalez** [comment]
Existing tests seem to pass here, though we should probably add the stuff in #30 as tests here.

**Comment by progrium** [comment]
Yeah, seems like great place for functional tests.

**Comment by michaelshobbs** [comment]
@Benjamin-Dobell care to add tests?

**Comment by Benjamin-Dobell** [comment]
Oh, I guess I probably should :wink:

I'll have to check-out how this herokuish-test thing works first.

**Comment by michaelshobbs** [comment]
@Benjamin-Dobell I'm on os x and grabbed `docker-machine`. Once you have a docker daemon, just run `make deps build-in-docker` to build the herokuish image from source. From there `make test` will run functional tests and `basht buildpacks/*/tests/*/test.sh` will run all of the buildpack tests. Hope this helps. Also we *should* probably document this. :smile:

**Comment by michaelshobbs** [comment]
@Benjamin-Dobell is this still an issue in the latest herokuish release? I can't seem to make it break anymore

**Pull request closed without merging**
