### PR TITLE
heroku base image

### PR DESCRIPTION
**Pull request by progrium**
:satisfied:

### CODE REVIEW

**Comment by bacongobbler** [comment]
here goes nothing

**Comment by kenips** [comment]
Question: if we're on cedar14, why are we still locking down on heroku buildpack versions? Shouldn't we go with latest all the time?

**Comment by bacongobbler** [comment]
master is not considered to be stable for the buildpacks.

**Comment by kenips** [comment]
not master, but latest released version? Oh as in there's no way to determine the latest tag?

**Comment by progrium** [comment]
It's going to be locked at some point in the chain because every time you build an app it's locking to a version. And once you install a system like Dokku, you don't want to pull the latest of every buildpack with every build. So ultimately there will be some form of "locking" downstream whether we do or not. 

Now if you assume that, you don't want to be locked with a broken version. Not all buildpacks do releases, so if you just use master you could get downstream locked with a broken version. Once you realize that you'll have to go upstream and pin it back to a working version. We can avoid that by testing here and locking here. 

So it consolidates pinning and "known good versions" here. The problem is keeping this updated with whatever the latest known good version of a buildpack is. At this point, most buildpacks work well enough it's only edge cases you need the latest good version. But that said, ideally we'd always have latest known good version. That's where this plan comes in:
https://github.com/gliderlabs/herokuish/wiki/UpstreamReleases

**Comment by kenips** [comment]
Cool. Thanks for the detailed response. I totally understand the design and the plan in making this easier.  I think because back then with dokku/buildpack we've been burnt a few times and the locking was necessarily. I'm just kind of curious if that effort in issuing PR for bumping buildpack versions are still necessarily given that we're running heroku buildpacks on heroku images. Sure, I'm just talking about the official heroku buildpacks on cedar14 here, so it might not apply to all. But wouldn't these buildpack always run on cedar14 in with the current effort in herokuish?

I'm not sure if I'm in the right path but seemingly if my assumption is true these can be treated as "trusted" buildpacks which can be closely tracked on their latest release, but perhaps I'm wrong.

**Comment by progrium** [comment]
heroku/cedar14 is *literally* cedarish. so other than the changes they make, there is no difference other than it's official.

next, i don't believe we have any insight into what buildpack release/version is being used by the heroku platform at any one time. if there are releases, which there are for the major ones, we can probably assume the latest release. but that's not necessarily the case as things can go wrong.

on top of that, because herokuish and docker, etc etc are still not EXACTLY heroku, there's always the possibility a latest working version of a buildpack works on heroku, but not with herokuish. 

so ultimately the best thing we can do is test test test, and automatically test and merge new buildpack versions/releases. right?

**Comment by kenips** [comment]
Heroku does publish their changes to buildpack here: https://devcenter.heroku.com/changelog, but you'll have to guess the version :)

Right. Got it. The automatic test plan sounds great!

**Pull request merged**
