### PR TITLE
Release v0.5.34

### PR DESCRIPTION
**Pull request by gjrdiesel**
### Changed

- @josegonzalez Update static to version v16 #738
- @josegonzalez Update go to version v160 #737
- @josegonzalez Update gradle to version v36 #736
- @josegonzalez Update python to version v205 #735
- @josegonzalez Update ruby to version v236 #734
- @gjrdiesel Update php to version v205 #733

### Fixed

- @IlyaSemenov Don't require binary in ci mode make (for circleci) #726

### CODE REVIEW

**Comment by josegonzalez** [comment]
Awh that looked good, I was going to merge when tests passed!

**Comment by gjrdiesel** [comment]
Sorry, you can open back up! Wasn’t sure how it’d release being a branch
from my fork.

**Comment by james-tu2** [comment]
Building of the new image with the v205 php buildpack is exactly what I was looking for. I'm plagued by that polyfill issue https://github.com/heroku/heroku-buildpack-php/pull/529 😢 

Thanks for updating this!

**Comment by gjrdiesel** [comment]
Thanks @josegonzalez

Question on the docker releases; Looking at [releases workflow](https://github.com/gliderlabs/herokuish/blob/master/.github/workflows/release.yml#L33-L47) looks like one should use either `latest-18` or `latest-20` tags correct? Or does `latest` get tagged at some point?

https://hub.docker.com/r/gliderlabs/herokuish/tags

**Comment by josegonzalez** [comment]
Oh, seems i need to manually tag latest. Mind filing a bug for us to get that tagged later?

**Pull request merged**
