### PR TITLE
Change VERSION env var to HEROKUISH_VERSION. Refs progrium/dokku#1066

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by progrium** [comment]
Almost! Just need to change this one as well: https://github.com/gliderlabs/herokuish/blob/master/include/herokuish.bash#L40

**Comment by joejwright** [comment]
@progrium @josegonzalez Thanks for the quick turnaround guys!

**Comment by josegonzalez** [comment]
@progrium bump!

**Comment by michaelshobbs** [comment]
refs progrium/dokku#1066

**Comment by sibsfinx** [comment]
:+1:

**Comment by progrium** [comment]
Trying to get this in but also Scala is failing tests, so trying to fix this first. Hey anybody want to help maintain Herokuish?

**Comment by progrium** [comment]
Can you rebase so I can make sure tests pass?

**Comment by josegonzalez** [comment]
Rebased!

**Comment by progrium** [comment]
Thanks. Also relevant: https://github.com/gliderlabs/herokuish#releases

**Pull request merged**
