### PR TITLE
Remove .git directory deletion upon build pack installation

### PR DESCRIPTION
**Pull request by natanrolnik**
Related to https://github.com/gliderlabs/herokuish/issues/311

### CODE REVIEW

**Comment by michaelshobbs** [comment]
it is ill-advised to have your git history accessible to the web app process on a web server on the internet. i'm 100% 👎 on this change.

cc: @josegonzalez @progrium

**Comment by natanrolnik** [comment]
@michaelshobbs did you even take a look at the issue described in #311? The buildpack has a submodule, not the app itself...
The git directory that is being deleted is the one from the buildpack... Is it the same one as the web app?!

**Comment by josegonzalez** [comment]
Reopening as I don’t think this is related to app history being present.

**Comment by michaelshobbs** [comment]
> The git directory that is being deleted is the one from the buildpack

understood

**Comment by michaelshobbs** [comment]
looking through the git history, it looks like we originally did a standard clone and then switched to shallow clone [here](https://github.com/gliderlabs/herokuish/commit/2cf5b0b967d3dd02c80e5a34754c78772960f5fa) but never removed the `rm` command below.

**Pull request merged**
