### PR TITLE
add herokuish.bash for work without go

### PR DESCRIPTION
**Pull request by pahaz**
Example:

    git clone https://github.com/pahaz/herokuish.git
    cd herokuish

    ./herokuish.bash help

    # install buildpacks
    cat buildpacks/*/buildpack* | sed 'N;s/\n/ /' > include/buildpacks.txt
    ./herokuish.bash buildpack install

    apt-get install python python-yaml daemontools -y

    TRACE=1 APP_PATH=buildpacks/buildpack-python/tests/python-flask USER= ./herokuish.bash buildpack build

### CODE REVIEW

**Comment by progrium** [comment]
Ok. Why? I really hate arbitrary PRs like this with absolutely no explanation.

**Comment by pahaz** [comment]
I think that one of the killer feature progrium/buildstep is that everything is written on bash, without preference of a programming language.
I think that the Python, Ruby, Node.js or Go (or any other language) programmer need to know bash at least at a basic level but may be not need to know other languages (not all of course). 
Because of this Dokku became so popular.

And now you must need to know Go language for understand how to work progrium/buildstep and herokuish. 

Another reason is compiling. With the compiled binary file is very difficult to understand what he is doing, it is difficult to check whether it is original or modified. compiling in this case does not give any advantages.

To facilitate understanding of the project logic you need to provide developers with an alternative (familiar to them) implementation. 

I think that the implementation at Bash is understandable to most users.

**Comment by Benjamin-Dobell** [comment]
Whilst I'd be inclined to say this is a pretty poor pull request. I wouldn't mind getting a dialog going as to the perceived advantages of using Go over Bash for a project like this.

**Comment by pahaz** [comment]
> Whilst I'd be inclined to say this is a pretty poor pull request

I aggree with you. This pull can be regarded as an offer. 
I can add a description and tests for this change. But first, it must be discussed.

So, what do you think about this proposal?

**Comment by mgood** [comment]
@pahaz when making a pull-request, please consider the original author's perspective as well as your own. Making statements like "compiling in this case does not give any advantages" is rude, because obviously @progrium did think their were advantages when he implemented it this way. If you don't understand something, please stop to ask the author why they did it that way first. Offering suggested improvements can be great, but make sure you understand the original intent first.

I will gladly try to answer polite questions about why Herokuish was implemented this way.

**Comment by pahaz** [comment]
> Making statements like "compiling in this case does not give any advantages" is rude

I beg your pardon. I do not want to offend the author. Compiling in this case the choice in the direction of improving the performance, but it degrade learnability and understandability. 

Perhaps my pull a few superfluous and rather write it as an example in the documentation. His task is not to replace Go (Go is the choice of the author) and add another implementation to improve the understandability.

If the author considers changes unnecessary, I can close the pull.

Links for read:
 - https://github.com/progrium/dokku/issues/1091
 - https://github.com/progrium/dokku/wiki/Refactoring
 - https://github.com/progrium/go-basher#motivation

**Comment by progrium** [comment]
I wanted to provide a more in-depth explanation, but I guess it's too late.
Basically, I would not call this project "written in Go" ... it's still
clearly over 90% Bash. The problem with Bash is distributing/packaging, and
certain things are not possible. With Go used (go-basher), we can
distribute this application as a single binary (perfect for
containers) that can live effectively as a single binary once installed,
and can leverage Go when a task is too complicated for Bash.

IMO learnability and understandability is not diminished much, but perhaps
could benefit from better documentation which I admit needs to change and
be expanded upon.

On Fri, May 15, 2015 at 8:25 AM, Pahaz Blinov <notifications@github.com>
wrote:

> Closed #32 <https://github.com/gliderlabs/herokuish/pull/32>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/pull/32#event-305831942>.
>



-- 
Jeff Lindsay
http://progrium.com

**Pull request closed without merging**
