### PR TITLE
only delete $app_path if $import_path is not empty

### PR DESCRIPTION
**Pull request by joshmanders**
This fixes https://github.com/gliderlabs/herokuish/issues/111

### CODE REVIEW

**Comment by michaelshobbs** [comment]
A couple comments 
- please use `[[` per https://github.com/progrium/bashstyle/blob/master/README.md
- I was unable to reproduce this bug. Do you have an example app/workflow that shows this breaking prior to your fix?

herokuish is an integral dependency of other projects so we want to be extra judicious when accepting PRs. thanks for the understanding.

**Comment by joshmanders** [comment]
The bug is that when you build an app and commit the container to a new image, it leaves `$import_path` there, but empty, the `herokuish.sh` file checks for it when it runs any command and as a result when you `/start web` on the new image it deletes `$app_path` and copies the empty directory to it's location. #111 goes into more depth of this.

What this does is it checks if it's there and not empty. Therefore if you run `/build` it will still work as intended, but `/start web` won't delete it and try to run a broken app.

**Comment by joshmanders** [comment]
No idea why ember failed in that test.

**Comment by michaelshobbs** [comment]
Ha! I couldn't recreate it because I was using a wrapper function I wrote that does the exact `build->commit->rm -rf /tmp/app->commit->start` flow described [here](https://github.com/gliderlabs/herokuish/issues/111#issuecomment-196762047).

Sorry for the derp and thanks for the PR!

**Comment by joshmanders** [comment]
Haha no problem, I've been hacking the heck out of this for my own usage, and added a few extra features that I'll probably be contributing back if anyone wants them.

**Comment by josegonzalez** [comment]
@joshmanders we're happy to get any/all features you have. A good herokuish release is good for more than just us :)

**Comment by joshmanders** [comment]
@josegonzalez My README is very sparse, just mentions being based off this, but when I get some time I'll flesh it out and go in depth on the new features and open issues up here for them and see if anyone is interested, if so I'll port them to my fork and submit PR's :)

**Pull request merged**
