### PR TITLE
buildpack-scala version bump (Play 2.4 support)

### PR DESCRIPTION
**Pull request by damirv**

### CODE REVIEW

**Comment by josegonzalez** [comment]
Seems like this just needs a rebuild.

**Comment by progrium** [comment]
Yeah Play keeps failing. Hoping this fixes it but so far the tests are still not passing on it.

**Comment by damirv** [comment]
@progrium Yes, it's mentioned [here](https://github.com/heroku/heroku-buildpack-play)

**Comment by progrium** [comment]
Should we drop Play 1 support? The buildpack is not currently working...

On Sun, Jul 5, 2015 at 11:20 AM, Damir Vandic <notifications@github.com>
wrote:

> @progrium <https://github.com/progrium> Yes, it's mentioned here
> <https://github.com/heroku/heroku-buildpack-play>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gliderlabs/herokuish/pull/33#issuecomment-118636195>.
>



-- 
Jeff Lindsay
http://progrium.com

**Comment by damirv** [comment]
I think that dropping support for Play 1.x apps is acceptable, especially because 1.x is no longer maintained ([here](https://github.com/playframework/playframework/branches) is a list of maintained branches).

**Comment by josegonzalez** [comment]
Play 1.x support has been removed, merging this in now :)

**Pull request merged**
