### PR TITLE
Explain `herokuish` for Heroku users

### PR DESCRIPTION
**Pull request by abitrolly**
See https://github.com/gliderlabs/herokuish/issues/321.

This is what I understood from the discussion.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Thats not quite true. If the host os you are on is compatible with the herokuish image, it should be possible to use the binary directly.

**Comment by abitrolly** [comment]
@josegonzalez what does mean for host to be compatible with the image? Which binary do you refer to? I understand that `herokuish` builds a Docker container image using buildpack. I haven't found a way to build and start the image with one command.

**Comment by josegonzalez** [comment]
Do you mean that you want it to create a docker container? If thats the case, your note makes a bit more sense but still isn't clear. We should just say that herokuish is used to create images, and that a `docker run` command can be used to run those images as a container.

**Comment by abitrolly** [comment]
I want it to run my app in a container with heroku-like environment to shorten my development cycle. Does that fit `herokuish` use case?

**Comment by josegonzalez** [comment]
Herokuish is used within the container both to trigger the `build` of an app with heroku buildpacks and as the init process. After that, the built image can be run as any other docker container.

Here is a [blog post](http://dokku.github.io/technology/comparing-buildpack-v3-to-herokuish) covering how the process works and how to interact with the resulting image.

**Comment by abitrolly** [comment]
@josegonzalez the blog post is great. However, it doesn't explain what a buildpack is. What is its function in life?

**Comment by josegonzalez** [comment]
https://www.heroku.com/elements/buildpacks

**Comment by abitrolly** [comment]
@josegonzalez unfortunately that description is highly dependent on understanding of Heroku platform. Basically, it says that buildpack is a `gcc` for Heroku. To understand why you need `gcc` there, you need to understand Heroku, which is not explained.

As a user of docker, podman, LXD and kubernetes, I would appreciate an explanation for kubernetes/container users.

**Comment by josegonzalez** [comment]
You're welcome to write that explanation, but what you've written above for this PR isn't it. Going to close it as the PR isn't useful, but also this conversation is better had over chat vs PR comments. Feel free to drop in on the gliderlabs slack community with any further questions.

**Comment by abitrolly** [comment]
@josegonzalez information in slack is not indexed by search engines, and people won't find it. To close the thread, a non-Heroku specific explanation of what buildpack is would be a good resolution. A link to some blog post would be fine.

I still have no idea how buildpack is different from Dockerfile, and why reinvent it.

**Comment by josegonzalez** [comment]
This project's focus isn't to describe what buildpacks are, nor to push people to using them. It's to replicate how buildpacks work on Heroku. Buildpacks more or less came from Heroku, so there isn't a great way to describe them without thinking about deployment and PaaS systems.

There is also [Cloud Native Buildpacks](https://buildpacks.io/), which is a project from a variety of buildpack technology maintainers, including Heroku. We don't support that here, but in the future will deprecate this project in favor of CNB. Perhaps that is a project that would interest you more, as it also has some of the marketing material you seem to want.

**Pull request closed without merging**
